<script setup>
import { ref } from "vue";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const props = defineProps({
    order: Object,
    show: Boolean,
});

const emit = defineEmits(["close"]);

function closeModal() {
    emit("close");
}

function downloadPDF() {
    const doc = new jsPDF();

    // ---------------- HEADER ----------------
    doc.setFontSize(20);
    doc.setTextColor(40, 40, 140);
    doc.text("🧾 Customer Invoice", 105, 15, { align: "center" });

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Generated by Your Company", 105, 22, { align: "center" });
    doc.setDrawColor(0);
    doc.line(14, 25, 196, 25); // horizontal line

    // ---------------- CUSTOMER INFO ----------------
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text("Customer Details", 14, 35);

    doc.setFontSize(10);
    doc.text(`Name: ${props.order?.customer?.name || "-"}`, 14, 42);
    doc.text(`Phone: ${props.order?.customer?.phone || "-"}`, 14, 48);
    doc.text(`Address: ${props.order?.customer?.address || "-"}`, 14, 54);

    // ---------------- ORDER INFO ----------------
    doc.setFontSize(12);
    doc.text("Order Details", 110, 35);

    doc.setFontSize(10);
    doc.text(`Order No: ${props.order?.order_number || "-"}`, 110, 42);
    doc.text(`Status: ${props.order?.status || "-"}`, 110, 48);
    doc.text(`Delivery Date: ${props.order?.delivery_date || "-"}`, 110, 54);
    doc.text(`Close Date: ${props.order?.close_date || "-"}`, 110, 60);

    // ---------------- NOTES ----------------
    let y = 70;
    if (props.order?.notes?.length) {
        doc.setFontSize(12);
        doc.text("📝 Notes:", 14, y);
        y += 6;
        doc.setFontSize(9);
        props.order.notes.forEach((note, i) => {
            doc.text(`- ${note.label}: ${note.text}`, 20, y);
            y += 5;
        });
    }

    // ---------------- ORDER ITEMS TABLE ----------------
    const items = props.order?.order_items || [];
    const tableData = items.map((item, i) => [
        i + 1,
        item?.colors || "-",
        item?.material_type || "-",
        item?.work_type || "-",
        `₹ ${item?.material_cost || 0}`,
        `₹ ${item?.stiching_cost || 0}`,
        `₹ ${item?.altering_cost || 0}`,
        `₹ ${item?.item_cost || 0}`,
    ]);

    autoTable(doc, {
        startY: y + 10,
        head: [
            [
                "#",
                "Colors",
                "Material",
                "Work Type",
                "Material Cost",
                "Stitching",
                "Altering",
                "Item Cost",
            ],
        ],
        body: tableData,
        theme: "grid",
        headStyles: { fillColor: [40, 40, 140], textColor: 255, halign: "center" },
        bodyStyles: { halign: "center" },
        styles: { fontSize: 9 },
    });

    // ---------------- TOTALS ----------------
    let afterTableY = doc.lastAutoTable.finalY + 15;

    const grandTotal = props.order?.total_amount || 0;
    const advance = props.order?.advance_paid || 0;
    const pending = grandTotal - advance;

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Summary", 14, afterTableY);

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text(`Grand Total: ₹ ${grandTotal}`, 14, afterTableY + 8);
    doc.text(`Advance Paid: ₹ ${advance}`, 14, afterTableY + 16);
    doc.text(`Pending Amount: ₹ ${pending}`, 14, afterTableY + 24);

    // ---------------- FOOTER ----------------
    doc.setDrawColor(0);
    doc.line(14, 285, 196, 285); // footer line
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text("Thank you for your order!", 105, 290, { align: "center" });

    // ---------------- SAVE ----------------
    doc.save(`Bill_${props.order?.order_number || "NA"}.pdf`);
}
</script>



<template>
    <div v-if="show" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
        <div class="bg-white rounded-lg shadow-lg w-full max-w-2xl p-6 relative">
            <button class="absolute top-3 right-3 text-gray-600 text-2xl" @click="closeModal">
                &times;
            </button>

            <h2 class="text-xl font-bold text-primary mb-4">🧾 Bill Details</h2>

            <div class="space-y-2 text-sm">
                <p><strong>Customer:</strong> {{ order?.customer?.name }}</p>
                <p><strong>Order Number:</strong> {{ order?.order_number }}</p>
                <p><strong>Grand Total:</strong> ₹ {{ order?.total_amount }}</p>
                <p><strong>Pending Amount:</strong> ₹ {{ order?.total_amount - (order?.advance_paid || 0) }}</p>
            </div>

            <!-- Action Buttons -->
            <div class="flex justify-end gap-4 mt-6">
                <button @click="downloadPDF" class="bg-primary text-white px-4 py-2 rounded-lg hover:bg-blue-700">
                    ⬇ Download PDF
                </button>
                <button class="bg-green-500 text-white px-4 py-2 rounded-lg hover:bg-green-600">
                    📲 Send via WhatsApp (coming soon)
                </button>
            </div>
        </div>
    </div>
</template>
