<script setup>
import { ref } from "vue";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Icon } from "@iconify/vue";

const props = defineProps({
    order: Object,
    show: Boolean,
});
const emit = defineEmits(["close"]);

function closeModal() {
    emit("close");
}

function formatCurrency(value) {
    if (!value) return "₹ 0.00";
    return `₹ ${Number(value).toLocaleString("en-IN", {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
    })}`;
}

async function getBase64ImageFromUrl(imageUrl) {
    const res = await fetch(imageUrl);
    const blob = await res.blob();
    return new Promise((resolve) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result);
        reader.readAsDataURL(blob);
    });
}

function formatDate(dateString) {
    if (!dateString) return "-";
    const d = new Date(dateString);
    const day = String(d.getDate()).padStart(2, "0");
    const month = String(d.getMonth() + 1).padStart(2, "0");
    const year = d.getFullYear();
    return `${day}-${month}-${year}`;
}

async function downloadPDF() {
    const doc = new jsPDF();

    // ---------------- HEADER BACKGROUND ----------------
    doc.setFillColor(40, 40, 140);
    doc.rect(0, 0, 210, 30, "F");

    // ---------------- ORGANIZATION LOGO + NAME ----------------
    const orgName = props.order?.organization?.organization_name || "Your Organization";
    const orgLogo = props.order?.organization?.organization_logo
        ? `${window.location.origin}/${props.order.organization.organization_logo}`
        : null;

    if (orgLogo) {
        try {
            const base64Logo = await getBase64ImageFromUrl(orgLogo);
            doc.addImage(base64Logo, "PNG", 10, 5, 20, 20);
        } catch (e) {
            console.warn("Logo load error:", e);
        }
    }

    doc.setFontSize(9);
    doc.setTextColor(255, 255, 255);
    doc.text(`Generated by ${orgName}`, 35, 12); // shifted a little up

    // ---------------- TITLE CENTER ----------------
    doc.setFontSize(18);
    doc.setTextColor(255, 255, 255);
    doc.text("Customer Invoice", 105, 25, { align: "center" }); // moved down for spacing

    // ---------------- CUSTOMER & ORDER INFO ----------------
    doc.setTextColor(0);
    doc.setFontSize(12);
    doc.text("Customer Details", 14, 40);

    doc.setFontSize(10);
    doc.text(`Name: ${props.order?.customer?.name || "-"}`, 14, 47);
    doc.text(`Phone: ${props.order?.customer?.phone || "-"}`, 14, 53);
    doc.text(`Address: ${props.order?.customer?.address || "-"}`, 14, 59);

    doc.setFontSize(12);
    doc.text("Order Details", 110, 40);

    doc.setFontSize(10);
    doc.text(`Order No: ${props.order?.order_number || "-"}`, 110, 47);
    doc.text(`Status: ${props.order?.status || "-"}`, 110, 53);
    doc.text(`Delivery Date: ${formatDate(props.order?.delivery_date)}`, 110, 59);
    doc.text(`Close Date: ${formatDate(props.order?.close_date)}`, 110, 65);

    // ---------------- TABLE ----------------
    const items = props.order?.order_items || [];
    const tableData = items.map((item, i) => [
        `Item-${i + 1}`,
        item?.colors || "-",
        item?.material_type || "-",
        item?.work_type || "-",
        formatCurrency(item?.material_cost),
        formatCurrency(item?.stiching_cost),
        formatCurrency(item?.altering_cost),
        formatCurrency(item?.item_cost),
    ]);

    autoTable(doc, {
        startY: 75,
        head: [["Items", "Colors", "Material", "Work Type", "Material Cost", "Stitching", "Altering", "Item Cost"]],
        body: tableData,
        theme: "grid",
        styles: { fontSize: 9, cellPadding: 3 },
        headStyles: { fillColor: [40, 40, 140], textColor: 255, halign: "center", fontSize: 10 },
        bodyStyles: { valign: "middle" },
        tableWidth: "auto",  // auto fit table inside page
        columnStyles: {
            0: { cellWidth: 18 },
            1: { cellWidth: 22 },
            2: { cellWidth: 28 },
            3: { cellWidth: 28 },
            4: { halign: "right", cellWidth: 25 },
            5: { halign: "right", cellWidth: 25 },
            6: { halign: "right", cellWidth: 25 },
            7: { halign: "right", cellWidth: 28 },
        },
        alternateRowStyles: { fillColor: [245, 245, 245] },
    });

    // ---------------- PAYMENT SUMMARY ----------------
    const afterTableY = doc.lastAutoTable.finalY + 15;
    const grandTotal = props.order?.total_amount || 0;
    const advance = props.order?.advance_paid || 0;
    const pending = grandTotal - advance;

    doc.setDrawColor(40, 40, 140);
    doc.setFillColor(240, 240, 255);
    doc.rect(14, afterTableY, 180, 35, "FD");

    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text("Payment Summary", 20, afterTableY + 10);

    doc.setFontSize(11);
    doc.text(`Grand Total: ${formatCurrency(grandTotal)}`, 20, afterTableY + 20);
    doc.text(`Advance Paid: ${formatCurrency(advance)}`, 20, afterTableY + 28);
    doc.text(`Pending Amount: ${formatCurrency(pending)}`, 20, afterTableY + 36);

    // ---------------- FOOTER ----------------
    doc.setDrawColor(0);
    doc.line(14, 285, 196, 285);
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text("Thank you for your order!", 105, 292, { align: "center" });

    doc.save(`Bill_${props.order?.order_number || "NA"}.pdf`);
}
</script>


<template>
    <div v-if="show" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
        <div class="bg-white rounded-2xl shadow-2xl w-full max-w-3xl p-8 relative">
            <button class="absolute top-4 right-4 text-gray-600 text-2xl hover:text-red-500 transition"
                @click="closeModal">
                &times;
            </button>

            <h2 class="text-2xl font-extrabold text-primary mb-6 text-center">Bill / Invoice Preview</h2>

            <!-- Customer + Order Info -->
            <div class="grid grid-cols-2 gap-6 bg-gray-50 p-4 rounded-lg border mb-6 text-sm">
                <div>
                    <h3 class="font-semibold text-primary mb-2">Customer</h3>
                    <p><strong>Name:</strong> {{ order?.customer?.name }}</p>
                    <p><strong>Phone:</strong> {{ order?.customer?.phone }}</p>
                    <p><strong>Address:</strong> {{ order?.customer?.address }}</p>
                </div>
                <div>
                    <h3 class="font-semibold text-primary mb-2">Order</h3>
                    <p><strong>No:</strong> {{ order?.order_number }}</p>
                    <p><strong>Status:</strong> {{ order?.status }}</p>
                    <p><strong>Delivery:</strong> {{ formatDate(order?.delivery_date) }}</p>
                    <p><strong>Close Date:</strong> {{ formatDate(order?.close_date) }}</p>
                </div>
            </div>

            <!-- Action Buttons -->
            <div class="flex justify-center gap-6 mt-6">
                <button @click="downloadPDF"
                    class="bg-primary text-white px-6 py-2 rounded-lg shadow flex items-center gap-2 transition">
                    <Icon icon="teenyicons:pdf-outline" width="18" height="18" />
                    Download PDF
                </button>
                <button class="bg-green-500 text-white px-6 py-2 rounded-lg shadow flex items-center gap-2 transition">
                    <Icon icon="bi:whatsapp" width="18" height="18" />
                    Send via WhatsApp
                </button>
            </div>
        </div>
    </div>
</template>
