name: Deploy to Development

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        server: ${{ fromJson(needs.create-deployment-artifacts.outputs.deployment-matrix) }}
    needs: create-deployment-artifacts

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install Node dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Create archive
        run: |
          mkdir -p artifacts
          tar -czf artifacts/${{ github.sha }}.tar.gz --exclude=*.git --exclude=node_modules --exclude=tests *

      - name: Upload via rsync
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          legacy_allow_rsa_hostkeys: "true"           # Optional if your server requires RSA
          path: ${{ github.sha }}.tar.gz              # Local archive to push
          remote_host: ${{ matrix.server.ip }}
          remote_user: ${{ matrix.server.username }}
          remote_port: ${{ matrix.server.port }}
          remote_path: ${{ matrix.server.path }}/artifacts
          remote_key: ${{ secrets.SERVER_SSH }}

      - name: Extract archive and create directories
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
        with:
          host: ${{ matrix.server.ip }}
          username: ${{ matrix.server.username }}
          key: ${{ secrets.SERVER_SSH }}
          port: ${{ matrix.server.port }}
          envs: GITHUB_SHA
          script: |
            sudo mkdir -p "${{ matrix.server.path }}/releases/${GITHUB_SHA}"
            sudo chown -R ubuntu:www-data ${{ matrix.server.path }}/releases

            sudo tar xzf ${{ matrix.server.path }}/artifacts/${GITHUB_SHA}.tar.gz \
              -C "${{ matrix.server.path }}/releases/${GITHUB_SHA}"

            sudo mkdir -p ${{ matrix.server.path }}/storage/{app,public,framework,logs}
            sudo mkdir -p ${{ matrix.server.path }}/storage/framework/{cache,sessions,testing,views}
            sudo mkdir -p ${{ matrix.server.path }}/storage/database
            sudo touch ${{ matrix.server.path }}/storage/database/database.sqlite

            sudo chmod -R 0777 ${{ matrix.server.path }}/storage
            sudo chown -R ubuntu:www-data ${{ matrix.server.path }}/storage
            sudo chown -R ubuntu:www-data ${{ matrix.server.path }}/bootstrap/cache
            sudo chmod -R 775 ${{ matrix.server.path }}/bootstrap/cache

      - name: Delete Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: app-build
          failOnError: false

      - name: Run before hooks
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
          RELEASE_PATH: ${{ matrix.server.path }}/releases/${{ github.sha }}
          ACTIVE_RELEASE_PATH: ${{ matrix.server.path }}/current
          STORAGE_PATH: ${{ matrix.server.path }}/storage
          BASE_PATH: ${{ matrix.server.path }}
        with:
          host: ${{ matrix.server.ip }}
          username: ${{ matrix.server.username }}
          key: ${{ secrets.SERVER_SSH }}
          port: ${{ matrix.server.port }}
          envs: GITHUB_SHA,RELEASE_PATH,ACTIVE_RELEASE_PATH,STORAGE_PATH,BASE_PATH
          script: |
            ${{ matrix.server.beforeHooks }}

      - name: Activate release
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
          RELEASE_PATH: ${{ matrix.server.path }}/releases/${{ github.sha }}
          ACTIVE_RELEASE_PATH: ${{ matrix.server.path }}/current
          STORAGE_PATH: ${{ matrix.server.path }}/storage
          BASE_PATH: ${{ matrix.server.path }}
          LARAVEL_ENV: ${{ secrets.STAGING_ENV }}
        with:
          host: ${{ matrix.server.ip }}
          username: ${{ matrix.server.username }}
          key: ${{ secrets.SERVER_SSH }}
          port: ${{ matrix.server.port }}
          envs: GITHUB_SHA,RELEASE_PATH,ACTIVE_RELEASE_PATH,STORAGE_PATH,BASE_PATH,LARAVEL_ENV
          script: |
            sudo printf "%s" "$LARAVEL_ENV" > "${BASE_PATH}/.env"
            sudo ln -s -f ${BASE_PATH}/.env $RELEASE_PATH
            sudo rm -rf ${RELEASE_PATH}/storage
            sudo ln -s -f $STORAGE_PATH $RELEASE_PATH
            sudo ln -s -n -f $RELEASE_PATH $ACTIVE_RELEASE_PATH
            sudo service php8.3-fpm reload
            sudo chown -R ubuntu:www-data $ACTIVE_RELEASE_PATH
            cd ${ACTIVE_RELEASE_PATH}

            sudo php artisan cache:clear
            sudo php artisan auth:clear-resets
            sudo php artisan view:cache
            sudo php artisan queue:restart
            sudo php artisan optimize
            sudo php artisan storage:link
            sudo composer install --optimize-autoloader

      - name: Run after hooks
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
          RELEASE_PATH: ${{ matrix.server.path }}/releases/${{ github.sha }}
          ACTIVE_RELEASE_PATH: ${{ matrix.server.path }}/current
          STORAGE_PATH: ${{ matrix.server.path }}/storage
          BASE_PATH: ${{ matrix.server.path }}
        with:
          host: ${{ matrix.server.ip }}
          username: ${{ matrix.server.username }}
          key: ${{ secrets.SERVER_SSH }}
          port: ${{ matrix.server.port }}
          envs: GITHUB_SHA,RELEASE_PATH,ACTIVE_RELEASE_PATH,STORAGE_PATH,BASE_PATH
          script: |
            export PATH=$PATH:/usr/local/bin:/home/ubuntu/.nvm/versions/node/…
            cd ${{ matrix.server.path }}/releases/${{ github.sha }}
            npm install puppeteer
            sudo chown -R ubuntu:www-data node_modules package-lock.json
            sudo chown -R ubuntu:www-data ${{ matrix.server.path }}/storage
            sudo chmod -R 755 ${{ matrix.server.path }}/storage
            sudo chown -R ubuntu:www-data "${{ matrix.server.path }}/releases/${GITHUB_SHA}/storage"
            sudo chmod -R 2775 "${{ matrix.server.path }}/releases/${GITHUB_SHA}/storage"
            ${{ matrix.server.afterHooks }}

      - name: Clean up
        uses: appleboy/ssh-action@master
        env:
          RELEASES_PATH: ${{ matrix.server.path }}/releases
          ARTIFACTS_PATH: ${{ matrix.server.path }}/artifacts
        with:
          host: ${{ matrix.server.ip }}
          username: ${{ matrix.server.username }}
          key: ${{ secrets.SERVER_SSH }}
          port: ${{ matrix.server.port }}
          script: |
            cd $ARTIFACTS_PATH && sudo ls -t | tail -n +3 | xargs rm -rf
            cd $RELEASES_PATH && sudo ls -t | tail -n +3 | xargs rm -rf
